sudo: false

language: scala

scala:
  - 2.11.11
  - 2.12.2

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test clean scalafmtTest

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2