version: '2'

volumes:
  epflbot-data:

services:

  bot:
    container_name: epflbot
    build: .
    restart: unless-stopped
    links:
      - elasticsearch:elasticsearch
      - logstash:logstash
    environment:
      - EPFLBOT_TOKEN
      - EPFLBOT_ELASTICSEARCH_HOST=elasticsearch
      - EPFLBOT_LOGSTASH_INTERFACE=logstash
      - EPFLBOT_LOGSTASH_APPENDER=STASH

  elasticsearch:
    container_name: epflbot-data
    image: elasticsearch:5
    restart: unless-stopped
    volumes:
      - epflbot-data:/usr/share/elasticsearch/data
    command: elasticsearch -E cluster.name=epflbot -E transport.host=0.0.0.0

  kibana:
    container_name: epflbot-interface
    image: kibana:5
    restart: unless-stopped
    links:
      - elasticsearch:elasticsearch

  nginx:
    container_name: epflbot-proxy
    image: beevelop/nginx-basic-auth
    restart: unless-stopped
    ports:
      - 7171:80
    links:
      - kibana:web
    environment:
      - HTPASSWD
      - FORWARD_PORT=5601

  logstash:
    container_name: epflbot-log
    image: logstash:5
    restart: unless-stopped
    volumes:
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
    links:
      - elasticsearch:elasticsearch
    entrypoint: "logstash -f /etc/logstash/conf.d/logstash.conf"
